// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psankgxevxiiyclrzntp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzYW5rZ3hldnhpaXljbHJ6bnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDA4NDAsImV4cCI6MjA3NjgxNjg0MH0.2-PDitmp85pNoWxrDIJ-V2ImNYCnryGZukxYeF1C_p8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);